baseURL = "https://www.soulful-craft.com/"
languageCode = "de-de"
title = "Gereifte Fr√ºchte der Vorstellungskraft"
theme = "PaperMod"


[[menu.main]]
name = "Frucht"
url = "/tags/frucht/"
weight = 1

[[menu.main]]
name = "DADA"
url = "/tags/dada/"
weight = 2

[params]
ShowCanonicalLink = true
customCSS = ["css/custom.css"]
description = "Poetische Fragmente zwischen DADA, Reife und Stille. Kein Feed. Kein Algorithmus. Nur Spuren."


