baseURL = 'https://www.soulful-craft.com/'
languageCode = 'de-de'
title = 'Soulful Craft'
theme = 'PaperMod'


[[menu.main]]
name = "Frucht"
url = "/tags/frucht/"
weight = 1

[[menu.main]]
name = "DADA"
url = "/tags/dada/"
weight = 2